micronaut.application.name=moedaestudantil

# Datasource
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/moedaestudantil
datasources.default.username=postgres
datasources.default.password=postgres

# JPA / Hibernate
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true

# CORS (frontend Angular em dev)
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins[0]=http://localhost:4200
micronaut.server.cors.configurations.web.allowed-methods[0]=GET
micronaut.server.cors.configurations.web.allowed-methods[1]=POST
micronaut.server.cors.configurations.web.allowed-methods[2]=PUT
micronaut.server.cors.configurations.web.allowed-methods[3]=DELETE
micronaut.server.cors.configurations.web.allowed-methods[4]=OPTIONS
micronaut.server.cors.configurations.web.allowed-headers[0]=Authorization
micronaut.server.cors.configurations.web.allowed-headers[1]=Content-Type

# Security / JWT
micronaut.security.authentication=bearer
micronaut.security.token.jwt.signatures.secret.generator.secret=${JWT_SECRET:pleaseChangeThisSecretInProductionItMustBeAtLeast256bits}
micronaut.security.token.jwt.generator.access-token.expiration=14400
